### ISSUE TITLE
Attitude direction wrong

### ISSUE THREAD

**Issue by HFMan** [eklynx/SimForeflightLink#15]
Hi- just tested this, and it works great!

One problem I noticed- when displaying the Attitude screen on foreflight, the bank shown/drawn is opposite of the actual bank angle of the plane.  Other than this, it worked great!

**Comment by eklynx** [comment]
hm...   i tested this out and thought it was correct.   will doublecheck and verify.

**Comment by eklynx** [comment]
Bug verified. will fix in next release

**Comment by eklynx** [comment]
Released in https://github.com/eklynx/SimForeflightLink/releases/tag/1.0.2
